name: CI/CD Telegram Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification to Telegram
        run: |
          curl -X POST "https://api.telegram.org/bot$7780994547:AAG-RIwyGThq6gGgKmgEY8qRCpH14njQoaE/sendMessage" \
          -d chat_id=-4553612431 \
          -d text="Novo commit na branch main: ${{ github.event.head_commit.message }} por ${{ github.event.head_commit.author.name }}"
